g4-common: add missing BT libs (libbt) for A13
* Fixes the following errors:
device/lge/g4-common/libbt/src/hardware.c:46:10: fatal error: 'bt_hci_bdroid.h' file not found

device/lge/g4-common/libbt/include/bt_vendor_brcm.h:33:10: fatal error: 'bt_vendor_lib.h' file not found

device/lge/g4-common/libbt/include/bt_vendor_brcm.h:33:10: fatal error: 'bt_vendor_hci.h' file not found

device/lge/g4-common/libbt/src/hardware.c:48:10: fatal error: 'esco_parameters.h' file not found

device/lge/g4-common/libbt/src/userial_vendor.c:36:10: fatal error: 'userial.h' file not found