g4-common: remove ro.adb.secure as it conflicts with some ROMs' config
* we will add it to the device variant trees as opposed to the common tree for each ROM

error: found duplicate sysprop assignments:
ro.adb.secure=0
ro.adb.secure=1