g4-common: add missing libs for hwaddrs and libqsap
* copy files from /system/core/libcutils/include

device/lge/g4-common/hwaddrs/hwaddrs.c:18:10: fatal error: 'system/core/libutils/include/utils/Log.h' file not found
device/lge/g4-common/libshims/libqsap_shim.c:6:10: fatal error: 'cutils/log.h' file not found