Revert "Revert sepolicy: Define sysfs_disk_stat properly"
It is required again, it seems:

[ 75% 102432/135037] build out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp
FAILED: out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp
/bin/bash -c "(out/host/linux-x86/bin/checkfc -e out/target/product/h815/obj/ETC/precompiled_sepolicy_intermediates/precompiled_sepolicy out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp ) && (out/host/linux-x86/bin/fc_sort -i out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp -o out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp )"
libsepol.context_from_record: type sysfs_disk_stat is not defined
libsepol.context_from_record: could not create context structure
out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp: line 1042 has invalid context u:object_r:sysfs_disk_stat:s0
libsepol.context_from_record: type sysfs_disk_stat is not defined
libsepol.context_from_record: could not create context structure
out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp: line 1042 has invalid context u:object_r:sysfs_disk_stat:s0
Error: could not load context file from out/target/product/h815/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp
09:27:16 ninja failed with: exit status 1

This reverts commit d743b3043f2ab6e64075afc047eb2c8d2362c134.