Revert "g4-common: Set ro.vndk.version to current"
error: found duplicate sysprop assignments:
ro.vndk.version=current
ro.vndk.version=35

This reverts commit ef5b5f44bb603a964e6662ca3ac961e33d780fb5.