g4-common: RIL: remove unused libril includes.
device/lge/g4-common/libril/ril.cpp:24:10: fatal error: 'cutils/jstring.h' file not found

The include is not used in A11: https://github.com/LineageOS/android_hardware_ril/commit/8c067224c09a9388ff0a6f7767aaade4ffe169d5

Test: treehugger
Change-Id: Id6ee53aa0e2a83ef40ce9219092f8a0f519b3471